{{- if or .Values.runnerRegistrationToken .Values.runnerToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitlab-runner.secret" . }}
  labels:
    app: {{ template "gitlab-runner.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  runner-registration-token: {{ default "" .Values.runnerRegistrationToken | b64enc | quote }}
  runner-token: {{ default "" .Values.runnerToken | b64enc | quote }}
{{- end -}}
